### ISSUE TITLE
URI::InvalidURIError happened in StoriesController#show

### ISSUE THREAD

**Issue by ssaunier** [lewagon/www#526]
**Message**

```
  bad URI(is not URI?): http://alumni.lewagon.org/api/v1/stories/discovering-the-digital-nomad-life-with-dimitri-bosch-teacher le-wagon-tokyo
```

**Backtrace (last 10 lines)**

```
vendor/ruby-2.4.2/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'
vendor/ruby-2.4.2/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
vendor/ruby-2.4.2/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
vendor/bundle/ruby/2.4.0/gems/rest-client-2.0.0/lib/restclient/request.rb:648:in `parse_url_with_auth!'
vendor/bundle/ruby/2.4.0/gems/rest-client-2.0.0/lib/restclient/request.rb:133:in `initialize'
vendor/bundle/ruby/2.4.0/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `new'
vendor/bundle/ruby/2.4.0/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `execute'
app/services/alumni_client.rb:107:in `get'
app/services/alumni_client.rb:24:in `block in story'
app/services/cache.rb:13:in `from_cache'
```

View on AppSignal: https://appsignal.com/lewagon/sites/58b435ece2954e1060183d3c/incidents/14

**Comment by cedricmenteau** [comment]
fixed #526
